version: '3.9'

services:
  graphql-server:
    build: ./graphql-server
    ports:  
      - "8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - graphql-net
  
  graphql-client:
    build: ./graphql-client
    ports:  
      - "3000"
    environment:
      GRAPHQL_SERVER_URI: ${GRAPHQL_SERVER_URI}
    networks:
      - graphql-net
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - graphql-server
    networks:
      - graphql-net

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - graphql-net


networks:
  graphql-net:
    driver: bridge

volumes:
  postgres_data: